from nle import nethack
from collections import defaultdict


# taken from: https://github.com/ngoodger/nle-language-wrapper/blob/main/src/main.cpp#L116

# TODO: adding object glyphs could be useful too

NLE_CMAP = [
      "dark area",
      "vertical wall",
      "horizontal wall",
      "northwest room corner",
      "northeast room corner",
      "southwest corner",
      "southeast corner",
      "cross wall",
      "t up wall",
      "t down wall",
      "t west wall",
      "t east wall",
      "doorway",
      "vertical open door",
      "horizontal open door",
      "vertical closed door",
      "horizontal closed door",
      "bars",
      "tree",
      "room floor",
      "dark room floor",
      "corridor floor",
      "lit corridor floor",
      "stairs up",
      "stairs down",
      "ladder up",
      "ladder down",
      "altar",
      "grave",
      "throne",
      "sink",
      "fountain",
      "pool",
      "ice",
      "lava",
      "vertical lowered drawbridge",
      "horizontal lowered drawbridge",
      "vertical raised drawbridge",
      "horizontal raised drawbridge",
      "air floor",
      "cloud floor",
      "water floor",
      "arrow trap",
      "dart trap",
      "falling rock trap",
      "squeaky board",
      "bear trap",
      "land mine",
      "rolling boulder trap",
      "sleeping gas trap",
      "rust trap",
      "fire trap",
      "pit",
      "spiked pit",
      "hole",
      "trap door",
      "teleportation trap",
      "level teleporter",
      "magic portal",
      "web",
      "statue trap",
      "magic trap",
      "anti magic trap",
      "polymorph trap",
      "vibrating square",
      "vertical beam",
      "horizontal beam",
      "left slant beam",
      "right slant beam",
      "dig beam",
      "flash beam",
      "boom left",
      "boom right",
      "shield 1",
      "shield 2",
      "shield 3",
      "shield 4",
      "poison cloud",
      "valid position",
      "swallow top left",
      "swallow top center",
      "swallow top right",
      "swallow middle left",
      "swallow middle right",
      "swallow bottom left",
      "swallow bottom center",
      "swallow bottom right",
      "explosion top left",
      "explosion top center",
      "explosion top right",
      "explosion middle left",
      "explosion middle center",
      "explosion middle right",
      "explosion bottom left",
      "explosion bottom center",
      "explosion bottom right",
]



NLE_TEXT_2_GLYPHS = defaultdict(int)

for i, item in enumerate(NLE_CMAP):
    NLE_TEXT_2_GLYPHS[item] = i + nethack.GLYPH_CMAP_OFF


