env: [
'mujoco_ant_umaze_dense2'
]

with_sol: [True]
sol_num_option_steps: [64]

reward_type: [
'diff',
]

with_flat_intrinsic_rewards: [False]
batch_size: [8192]
rollout: [256]
recurrence: [256]
mujoco_ctrl_cost_weight: [0.0, 0.01]
mujoco_contact_cost_weight: [0.0]
reward_scale: [1.0, 3.0, 10.0]

normalize_input: [False]

#adaptive_stddev: [False]
exploration_loss: ['entropy']
exploration_loss_coeff: [0.0001]


mujoco_max_episode_steps: [1000]
#num_epochs: [2]
#num_workers: [8]
#num_envs_per_worker: [8]



