env: ['minihack_zombie_horde']

with_sol: [False]
with_flat_intrinsic_rewards: [False]

llm_reward_type: ['motif_legacy']
motif_reward_dir: ['/private/home/mikaelhenaff/projects/rl-llm3/motif/train_dir/reward_saving_dir/standard_reward_llama2']


reward_scale: [0.01]
llm_reward_coeff: [0.01, 0.03, 0.1, 0.3, 1.0]

reward_scale_score: [1.0]
reward_scale_health: [0.0]

character: [
'mon-hum-neu-mal',
]

rollout: [256]
gamma: [0.99]
value_loss_coeff: [0.5]
exploration_loss_coeff: [0.003]
reward_clip: [100.0]
model: ['SymbolicGlyphNet']
map_input_type: ['glyphs']
inv_input_type: ["none"]
crop_dim: [12]
num_epochs: [1]
batch_size: [32768]
