
env: [
#'mujoco_ant_umaze_dense2'
'mujoco_point_umaze_dense',
]

reward_type: [
#'default',
'diff',
#'x_velocity', 
#'x_velocity_survive',
]

with_sol: [False]
with_flat_intrinsic_rewards: [False]

async_rl: [True]

batch_size: [32768]
rollout: [1024]
recurrence: [1024]
mujoco_ctrl_cost_weight: [0.0]
mujoco_contact_cost_weight: [0.0]
reward_scale: [3.0, 10.0]
normalize_input: [True, False]
learning_rate: [0.001, 0.00295]
max_grad_norm: [0.1, 3.5]
value_loss_coeff: [0.5, 1.3]
num_batches_per_epoch: [1, 4]

adaptive_stddev: [True]
#exploration_loss_coeff: [0.0, 0.0001]
exploration_loss_coeff: [0.0]
mujoco_max_episode_steps: [1000]
num_epochs: [10]
num_workers: [8]
num_envs_per_worker: [8]



