env: [
'mujoco_point_gmaze_dense',
'mujoco_point_umaze_dense',
]

train_for_env_steps: [20000000]


reward_type: [
'diff',
#'sparse', 
]

with_sol: [True]
sol_controller_reward_scale: [1.0]
sol_controller_exploration_scale: [1.0]
sol_num_option_steps: [-1, 1, 2, 4, 8, 16, 32, 64, 128]
sol_iso_loss_coeff: [0.0]

sol_option_rewards: [
'north,south,east,west,goal',
'goal1,goal2,goal3,goal4,goal5'
]


reward_scale_options: [1.0]
reward_scale_goal: [1.0]

with_flat_intrinsic_rewards: [False]

async_rl: [True]

batch_size: [32768]
rollout: [1024]
recurrence: [1024]
mujoco_ctrl_cost_weight: [0.0]
mujoco_contact_cost_weight: [0.0]
mujoco_success_reward_weight: [5.0]
reward_scale: [1.0]
normalize_input: [False]
learning_rate: [0.001]
max_grad_norm: [0.1]
value_loss_coeff: [0.5]
num_batches_per_epoch: [1]

adaptive_stddev: [True]
exploration_loss_coeff: [0.0001]
mujoco_max_episode_steps: [500]
num_epochs: [10]
num_workers: [8]
num_envs_per_worker: [8]

