
env: [
'mujoco_point_umaze_sparse',
'mujoco_point_gmaze_sparse',
]

reward_type: [
'default',
'diff',
]

with_sol: [False]
with_flat_intrinsic_rewards: [False]

async_rl: [True]

batch_size: [32768]
rollout: [1024]
recurrence: [1024]
mujoco_ctrl_cost_weight: [0.0]
mujoco_contact_cost_weight: [0.0]
reward_scale: [10.0]
normalize_input: [False]
learning_rate: [0.001]
max_grad_norm: [0.1]
value_loss_coeff: [0.5]
num_batches_per_epoch: [1]

adaptive_stddev: [True]
#exploration_loss_coeff: [0.0, 0.0001]
exploration_loss_coeff: [0.0]
mujoco_max_episode_steps: [100, 200, 300, 500]
num_epochs: [10]
num_workers: [8]
num_envs_per_worker: [8]



