env: [
'mujoco_ant_umaze_dense_fixed',
]

mujoco_ctrl_cost_weight: [0.01]
mujoco_contact_cost_weight: [0.0000005]
mujoco_survive_cost_weight: [1.0]
mujoco_terminate_when_unhealthy: [False]
mujoco_success_reward_weight: [50.0]
mujoco_max_episode_steps: [2000]

reward_type: [
'diff',
#'sparse',
]

with_sol: [True]
sol_controller_reward_scale: [1.0]
sol_controller_exploration_scale: [0.1]
sol_num_option_steps: [512]
sol_iso_loss_coeff: [0.0001]

reward_scale_options: [1.0]
reward_scale_goal: [1.0]

with_flat_intrinsic_rewards: [False]

async_rl: [True]


batch_size: [32768, 8192]
rollout: [2048]
recurrence: [2048]
reward_scale: [1.0]
normalize_input: [False]
learning_rate: [0.001]
max_grad_norm: [0.1]
value_loss_coeff: [0.5]
num_batches_per_epoch: [1]

adaptive_stddev: [True]
exploration_loss_coeff: [0.0001]
num_epochs: [1, 10]
num_workers: [8]
num_envs_per_worker: [8, 12]

