program: train_dnd_vf.py
entity: michaelmatthews
project: dnd
method: random
metric:
  goal: maximize
  name: train_loss
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_boolean_flags}
parameters:
  lr:
    values: [1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9]
  batch-size:
    values: [4, 8, 16]
  embedding-dim:
    values: [32, 64, 128, 256, 512]
  max-token-length:
    values: [2, 4, 8, 16]