env: ['nethack_challenge']

with_sol: [False]
with_flat_intrinsic_rewards: [True]

reward_scale: [0.01]

reward_scale_score: [1.0]
reward_scale_eating: [0.0, 0.01, 0.03, 0.1, 0.3, 1.0]

character: [
'cav-hum-neu-mal',
'wiz-hum-neu-mal',
'pri-hum-neu-mal',
]

token_embed_std: [0.001]

inv_encoder_type: [0, 4]
inv_query_heads: [4, 8]
#inv_query_std: [0.0001, 0.001, 0.01, 0.1, 1.0]
inv_query_std: [0.1]


rollout: [256]
gamma: [0.99]
value_loss_coeff: [0.5]
exploration_loss_coeff: [0.003]
reward_clip: [10000.0]

model: ['SymbolicGlyphNet']
map_input_type: ['glyphs']
inv_input_type: ["tok"]

crop_dim: [12]
num_epochs: [1]
batch_size: [32768]
