env: ['nethack_challenge']

with_sol: [True]

#sol_option_rewards: ['scout,eating,dlvl_up']
sol_option_rewards: ['scout,eating,dlvl_up,experience']
sol_controller_reward_key: ['scout']
sol_controller_reward_scale: [0.001]
sol_controller_exploration_scale: [1.0, 3.0, 10.0]
sol_num_option_steps: [-1]
sol_iso_loss_coeff: [0.0]
sol_bootstrap_on_option_switch: [True]

sol_multi_num_coefs: [3]
sol_multi_coef_spacing: ['linear']
sol_multi_normalise_coefs: ['true']
sol_controller_action_space: ['multidiscrete']


reward_scale: [0.01]
reward_scale_scout: [1.0]
reward_scale_score: [0.0]
reward_scale_experience: [4.0]
reward_scale_health: [0.0]
reward_scale_eating: [0.0, 0.03, 0.1]
reward_scale_dlvl_up: [100.0]
reward_scale_armor: [0.0]

character: [
'sam-hum-law-mal',
]

use_spellcasting_wrapper: [False]
use_dungeon_overview_wrapper: [True]


inv_encoder_type: ['att']
inv_query_heads: [4]


rollout: [256]
gamma: [0.999]
value_loss_coeff: [0.5]
exploration_loss_coeff: [0.003]
reward_clip: [10000.0]

max_token_length: [12]

model: ['SymbolicGlyphTokenNetEmbeddingBag']
map_input_type: ['glyphs']
inv_input_type: ["tok"]

crop_dim: [12]
num_epochs: [1]
batch_size: [32768]

num_workers: [64]
