env: ['nethack_challenge']

with_sol: [False]
with_flat_intrinsic_rewards: [False]

reward_scale: [0.01]

reward_scale_score: [1.0]

character: [
'mon-hum-neu-mal',
#'ran-hum-neu-mal',
#'wiz-hum-neu-fem',
]

rollout: [256]
gamma: [0.99]
value_loss_coeff: [0.5]
exploration_loss_coeff: [0.003]
reward_clip: [10000.0]
map_input_type: ['glyphs']

#model: ['SymbolicGlyphNet']
#inv_input_type: ["none"]

model: ['SymbolicGlyphTokenNet']
inv_input_type: ["tok"]

crop_dim: [12]
num_epochs: [1]
batch_size: [32768]
num_envs_per_worker: [40]
