env: [
'minihack_armor_uncursed',
'minihack_armor_inv'
]

with_sol: [False]
with_flat_intrinsic_rewards: [False]

reward_scale: [0.01, 0.1, 1.0, 10.0]



character: ['wiz-hum-neu-fem']
rollout: [256]
gamma: [0.99]
value_loss_coeff: [0.5]
exploration_loss_coeff: [0.003]
reward_clip: [10000.0]
#model: ['SymbolicGlyphTokenNet']
model: ['SymbolicGlyphNet']
map_input_type: ['glyphs']
inv_input_type: ["none"]
crop_dim: [12]
num_epochs: [1]
batch_size: [32768]
num_workers: [16]
num_envs_per_worker: [20]
