env: [
'craftium_open_world',
]

sil_coeff: [0.0, 0.01, 0.1, 1.0, 10.0]
max_episode_steps: [2000]

rollout: [256]
learning_rate: [0.00025]
gamma: [0.99]
num_epochs: [1]
reward_scale: [0.01]
exploration_loss_coeff: [0.003]
env_frameskip: [4]
num_envs_per_worker: [1]
num_workers: [72]

normalize_input: [True]
normalize_input_keys: ['info_stats img']
batch_size: [4096]
train_for_env_steps: [500000000]
worker_num_splits: [1]
stats_avg: [20]
experiment_summaries_interval: [20]

fps_max: [500]
sync_mode: [True]
mt_wd: ["/checkpoint/mikaelhenaff/tmp01/luanti"]
num_workers_fail_before_stop_training: [100000000000]
