env: [
#'craftium_chop_tree',
#'craftium_room',
#'craftium_spiders_attack',
#'craftium_speleo',
'craftium_open_world',
#'craftium_open_world_mod',
#'craftium_small_room',
]

max_episode_steps: [1000]

rollout: [128]
learning_rate: [0.00025]
gamma: [0.99]
num_epochs: [4]
reward_scale: [0.01]
exploration_loss_coeff: [0.003]
env_frameskip: [4]
num_envs_per_worker: [1]
num_workers: [64]
#num_workers: [1]
normalize_input: [True]
batch_size: [4096]
train_for_env_steps: [500000000]
worker_num_splits: [1]
stats_avg: [20]
experiment_summaries_interval: [20]
fps_max: [500]
sync_mode: [True]
mt_wd: ["/checkpoint/mikaelhenaff/tmp00/luanti"]
num_workers_fail_before_stop_training: [100000000000]
#mt_wd: ["./"]
